#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/dreamstore/Documents/Robota/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/dreamstore/Documents/Robota/Devcraft/Plugin_repo/5/onegini-flutter-sdk-wrapper/example"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/dreamstore/Documents/Robota/Devcraft/Plugin_repo/5/onegini-flutter-sdk-wrapper/example/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "FLUTTER_BUILD_NAME=1.0.2"
export "FLUTTER_BUILD_NUMBER=1.0.2"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/dreamstore/Documents/Robota/Devcraft/Plugin_repo/5/onegini-flutter-sdk-wrapper/example/.dart_tool/package_config.json"
