name: onegini
description: Onegini Mobile Flutter plugin.
version: 1.0.0-dev.1
homepage: https://www.onegini.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.onegini.mobile.sdk.flutter
        pluginClass: OneginiPlugin
      ios:
        pluginClass: OneginiPlugin
