name: onegini
description: The Onegini Flutter Plugin is a plugin that allows you to utilize the Onegini Mobile SDKs in your Flutter applications.
version: 1.2.0
homepage: https://www.onegini.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pigeon:
    git:
      url: git@github.com:flutter/packages.git
      path: packages/pigeon
      ref: 43bfaaf55c0bd6b550bf2cb9af940a00b046bd07
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.onegini.mobile.sdk.flutter
        pluginClass: OneginiPlugin
      ios:
        pluginClass: OneginiPlugin
