package com.onegini.mobile.onegini_example;

import android.os.Build;
import com.onegini.mobile.sdk.android.model.OneginiClientConfigModel;

public class OneginiConfigModel implements OneginiClientConfigModel {

  /* Config model generated by SDK Configurator version: v5.3.0 */

  private final String appIdentifier = "FlutterExampleApp";
  private final String appPlatform = "android";
  private final String redirectionUri = "oneginiexample://loginsuccess";
  private final String appVersion = "1.1.0";
  private final String baseURL = "https://mobile-security-proxy.test.onegini.com";
  private final String resourceBaseURL = "https://mobile-security-proxy.test.onegini.com/resources/";
  private final String keystoreHash = "8295209ea429be2cd6eb57a2d0c91c718314392b415799ab852e9e7b81aae986";
  private final int maxPinFailures = 3;
  private final String serverPublicKey = "7890DAAA329A2443B757B48A0DEFE6D5C5EAEE87C23209AA0C1F51B87C963406";
  private final String serverType = "access";
  private final String serverVersion = "fe2674a";

  public String getAppIdentifier() {
    return appIdentifier;
  }

  public String getAppPlatform() {
    return appPlatform;
  }

  public String getRedirectUri() {
    return redirectionUri;
  }

  public String getAppVersion() {
    return appVersion;
  }

  public String getBaseUrl() {
    return baseURL;
  }

  public String getResourceBaseUrl() {
    return resourceBaseURL;
  }

  public int getCertificatePinningKeyStore() {
    return R.raw.keystore;
  }

  public String getKeyStoreHash() {
    return keystoreHash;
  }

  public String getDeviceName() {
    return Build.BRAND + " " + Build.MODEL;
  }

  public String getServerPublicKey() {
    return serverPublicKey;
  }

    public String getServerType() {
    return serverType;
  }

    public String getServerVersion() {
    return serverVersion;
  }

  @Override
  public String toString() {
    return "ConfigModel{" +
            "  appIdentifier='" + appIdentifier + "'" +
            ", appPlatform='" + appPlatform + "'" +
            ", redirectionUri='" + redirectionUri + "'" +
            ", appVersion='" + appVersion + "'" +
            ", baseURL='" + baseURL + "'" +
            ", maxPinFailures='" + maxPinFailures + "'" +
            ", resourceBaseURL='" + resourceBaseURL + "'" +
            ", keyStoreHash='" + getKeyStoreHash() + "'" +
            ", serverPublicKey='" + serverPublicKey + "'" +
            ", serverType='" + serverType + "'" +
            ", serverVersion='" + serverVersion + "'" +
            "}";
  }
}
